#!/usr/bin/python3.4

import json
import sys


class JSONExtendEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, set):
            return list(obj)
        if isinstance(obj, bytes):
            return obj.decode('utf-8')
        return json.JSONEncoder.default(self, obj)

print(
    json.dumps(
        json.loads(''.join(sys.stdin.readlines())),
        indent=4,
        cls=JSONExtendEncoder
    )
)
